//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenInsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model_od_prem_amt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Model_od_prem_amt()
        {
            this.Vehicle_Info = new HashSet<Vehicle_Info>();
        }
    
        public string Model_Name { get; set; }
        public string vehicle_type { get; set; }
        public Nullable<double> Veh_based_od_prem { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public Nullable<decimal> market_price { get; set; }
    
        public virtual Brand_Names Brand_Names { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_Info> Vehicle_Info { get; set; }
    }
}
