//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenInsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class No_Claim_Bonus
    {
        public int id { get; set; }
        public Nullable<int> No_of_cons_yr_not_claimed { get; set; }
        public Nullable<int> Discount_percentage { get; set; }
    }
}
