//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenInsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_id { get; set; }
        public string Policy_No { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> Payment_date { get; set; }
        public string Card_type { get; set; }
        public Nullable<int> Card_number { get; set; }
        public Nullable<System.DateTime> Exp_date { get; set; }
        public string Payment_status { get; set; }
    
        public virtual Subscription_plan Subscription_plan { get; set; }
        public virtual User_Registration User_Registration { get; set; }
    }
}
