//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenInsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription_plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription_plan()
        {
            this.Claim_Insurance = new HashSet<Claim_Insurance>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int Policy_No { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Policy_plan_id { get; set; }
        public string Reg_No { get; set; }
        public Nullable<System.DateTime> Sub_date { get; set; }
        public string Status_of_sub { get; set; }
        public Nullable<decimal> Market_price { get; set; }
        public Nullable<decimal> IDV { get; set; }
        public Nullable<decimal> Total_tp_prem_amt { get; set; }
        public Nullable<decimal> Total_od_prem_amt { get; set; }
        public Nullable<decimal> Total_Payable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim_Insurance> Claim_Insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Policy_Plans Policy_Plans { get; set; }
        public virtual Vehicle_Info Vehicle_Info { get; set; }
        public virtual User_Registration User_Registration { get; set; }
    }
}
