//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenInsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Third_Party_Prem
    {
        public int id { get; set; }
        public Nullable<int> Vehicle_CC_Min { get; set; }
        public Nullable<int> Vehicle_CC_Max { get; set; }
        public string Vehicle_Type { get; set; }
        public Nullable<int> Fixed_TP_Prem { get; set; }
    }
}
